# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      ##- restore_cache:
          ##keys:
          ##- v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          ##- v1-dependencies-
      
      # Install command to upload to github pages
      - run: sudo npm install -g angular-cli-ghpages

      - run: 
          name: Install Packages
          command: sudo npm install

       #- save_cache:
          #paths:
            #- node_modules
          #key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
          
      - run: 
          name: Generate Build
          command: ng build --prod --output-path docs --base-href "CICD-Demo"

      # Deploy to github pages
      - run:
          name: Deploy to Github Pages
          comand: ngh