version: 2
jobs:
  build:
    working_directory: ~/repo
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: 
          name: Unit Tests
          command: npm run test
      - run: 
          name: build production
          command: npm run build-prod

  deploy-prod:
      working_directory: ~/repo
      docker:
        - image: circleci/node:8-browsers
      steps:
        - run:
            name: Copy index.html to 404.html
            command: 'cp docs/index.html docs/404.html'
        - run:
            name: Deploy if build & tests pass and branch is master
            command: |
              ./scripts/deploy-ghpages.sh      

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-prod:
        requires:
          - build
        filters:
          branches:
            only: master
